version: '3.0'
services:

    # Nginx Service
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./config/nginx/default.conf:/conf.d/default.conf